### ISSUE TITLE
doesn't stop greylisting

### ISSUE THREAD

**Issue by chromerobv** [vstakhov/rmilter#40]
i recently upgraded to 1.6.5 and for some reason it will not stop greylisting items.
i sent something over an hour ago and it still says to try again later.

Oct 18 22:53:36 c6 postfix/smtpd[17013]: connect from mail-ob0-f177.google.com[209.85.214.177]
Oct 18 22:53:36 c6 postfix/smtpd[17013]: setting up TLS connection from mail-ob0-f177.google.com[209.85.214.177]
Oct 18 22:53:36 c6 postfix/smtpd[17013]: Anonymous TLS connection established from mail-ob0-f177.google.com[209.85.214.177]: TLSv1.2 with cipher AES128-GCM-SHA256 (128/128 bits)
Oct 18 22:53:36 c6 postfix/smtpd[17013]: 6BAC0280100: client=mail-ob0-f177.google.com[209.85.214.177]
Oct 18 22:53:36 c6 postfix/cleanup[16874]: 6BAC0280100: message-id=<CABXkipAnsvew6Q=A8PxFm8kesBjoC5PqwGNdti6du1Ycp=GVjQ@mail.gmail.com>
Oct 18 22:53:45 c6 postfix/cleanup[16874]: 6BAC0280100: milter-reject: END-OF-MESSAGE from mail-ob0-f177.google.com[209.85.214.177]: 4.7.1 Service unavailable - try again later; from=<phynias@gmail.com> to=<sideshow@greeneggsnspam.com> proto=ESMTP helo=<mail-ob0-f177.google.com>
Oct 18 22:53:45 c6 postfix/smtpd[17013]: disconnect from mail-ob0-f177.google.com[209.85.214.177]

the hard part is rmilter no longer shows up in any of my logs. normally when i start it i see something in my maillog that says:
Oct 18 22:51:01 c6 rmilter[16865]: main: starting rmilter version 1.6.5
Oct 18 22:51:01 c6 rmilter[16865]: reload_thread: starting...

 and then more rmilter log entries as things happen, now nothing.

...here is my config

# Sample config file for rmilter
# $Id$
#

# .include - directive to include other config file
#.include /etc/rmilter/rmilter-grey.conf

# pidfile - path to pid file
# Default: pidfile = /var/run/rmilter.pid

pidfile = /var/run/rmilter/rmilter.pid;

clamav {
        # servers - clamav socket definitions in format:
        # /path/to/file
        # host[:port]
        # sockets are separated by ','
        # Default: empty
        #servers = localhost;
        servers = /var/run/clamav/clamd.sock;
        # connect_timeout - timeout in miliseconds for connecting to clamav
        # Default: 1s
        connect_timeout = 1s;

        # port_timeout - timeout in miliseconds for waiting for clamav port response
        # Default: 4s
        port_timeout = 4s;

        # results_timeout - timeout in miliseconds for waiting for clamav response
        # Default: 20s
        results_timeout = 20s;

        # error_time - time in seconds during which we are counting errors
        # Default: 10
        error_time = 10;

        # dead_time - time in seconds during which we are thinking that server is down
        # Default: 300
        dead_time = 300;

        # maxerrors - maximum number of errors that can occur during error_time to make us thinking that 
        # this upstream is dead
        # Default: 10
        maxerrors = 10;
};

spamd {
        # use rspamd action for greylisting
        spamd_greylist = yes;
        
        # use rspamd action for messages
        spamd_soft_fail = yes;

        # add extended headers for messages
        extended_spam_headers = yes;

        # servers - spamd socket definitions in format:
        # /path/to/file
        # host[:port]
        # sockets are separated by ','
        # is server name is prefixed with r: it is rspamd server
        # Default: empty
        servers = r:localhost:11333;

        # also_check - extra spamd servers to check
        #also_check = r:spam.example.com;

        # diff_dir - path where to write messages that have different results from main and extra checks
        #diff_dir = /var/run/rmilter/diffmsg;

        # connect_timeout - timeout in milliseconds for connecting to spamd
        # Default: 1s
        connect_timeout = 1s;

        # results_timeout - timeout in milliseconds for waiting for spamd response
        # Default: 20s
        results_timeout = 20s;

        # error_time - time in seconds during which we are counting errors
        # Default: 10
        error_time = 10;

        # dead_time - time in seconds during which we are thinking that server is down
        # Default: 300
        dead_time = 300;

        # maxerrors - maximum number of errors that can occur during error_time to make us thinking that 
        # this upstream is dead
        # Default: 10
        maxerrors = 10;

        # reject_message - reject message for spam
        # Default: "Spam message rejected; If this is not spam contact abuse"
        reject_message = "Spam message rejected; If this is not spam contact abuse";

        # whitelist - list of ips or nets that should be not checked with spamd
        # Default: empty
        whitelist = 127.0.0.1/32;

        # rspamd_metric - metric for using with rspamd
        # Default: "default"
        rspamd_metric = "default";
};

memcached {
        # servers_grey - memcached servers for greylisting in format:
        # host[:port][, host[:port]]
        # It is possible to make memcached mirroring, its syntax is {server1, server2}
        servers_grey = localhost;

        # servers_white - memcached servers for whitelisting in format similar to that is used
        # in servers_grey
        # servers_white = {localhost, mcgi12.example.com}, mcgi18.example.com:11211;

        # servers_limits - memcached servers used for limits storing, can not be mirrored
        servers_limits = localhost;

        # servers_id - memcached servers used for message id storing, can not be mirrored
        servers_id = localhost;

        # id_prefix - prefix for extracting message ids from memcached
        # Default: empty (no prefix is prepended to key)
        id_prefix = "message_id.";

        # grey_prefix - prefix for extracting greylisted records from memcached
        # Default: empty (no prefix is prepended to key)
        grey_prefix = "grey.";

        # id_prefix - prefix for extracting whitelisted records from memcached
        # Default: empty (no prefix is prepended to key)
        white_prefix = "white.";

        # connect_timeout - timeout in miliseconds for waiting for memcached
        # Default: 1s
        connect_timeout = 1s;

        # error_time - time in seconds during which we are counting errors
        # Default: 10
        error_time = 10;

        # dead_time - time in seconds during which we are thinking that server is down
        # Default: 300
        dead_time = 300;

        # maxerrors - maximum number of errors that can occur during error_time to make us thinking that 
        # this upstream is dead
        # Default: 10
        maxerrors = 10;

        # protocol - protocol that is using for connecting to memcached (tcp or udp)
        # Default: udp
        protocol = tcp;
};

# bind_socket - socket credits for local bind:
# unix:/path/to/file - bind to local socket
# inet:port@host - bind to inet socket
# Default: bind_socket = unix:/var/tmp/rmilter.sock;

bind_socket = unix:/var/run/rmilter/rmilter.sock;
# tempdir - path to directory that contains temporary files
# Default: $TMPDIR

tempdir = /var/spool/tmp;

# max_size - maximum size of scanned mail with clamav and dcc
# Default: 0 (no limit)
max_size = 10M;

# spf_domains - path to file that contains hash of spf domains
# Default: empty

#spf_domains = example.com;

# use_dcc - whether use or not dcc system
# Default: no

use_dcc = no;

# rule definition:
# rule {
#       accept|discard|reject|tempfail|quarantine "[message]"; <- action definition
#       [not] connect <regexp> <regexp>; <- conditions
#       helo <regexp>;
#       envfrom <regexp>;
#       envrcpt <regexp>;
#       header <regexp> <regexp>;
#       body <regexp>;
# };

# limits section
limits {
        # Whitelisted ip or networks
        #limit_whitelist = 194.67.45.4/32;
        # Whitelisted recipients
        limit_whitelist_rcpt =  postmaster, mailer-daemon;
        # Addrs for bounce checks
        limit_bounce_addrs = postmaster, mailer-daemon, symantec_antivirus_for_smtp_gateways, <>, null, fetchmail-daemon;
        # Limit for bounce mail
        limit_bounce_to = 5:0.000277778;
        # Limit for bounce mail per one source ip
        limit_bounce_to_ip = 5:0.000277778;
        # Limit for all mail per recipient
        limit_to = 20:0.016666667;
        # Limit for all mail per one source ip
        limit_to_ip = 30:0.025;
        # Limit for all mail per one source ip and from address
        limit_to_ip_from = 100:0.033333333;
};

beanstalk {
        # List of beanstalk servers, random selected
        #servers = bot01.example.com:3132;

        # Address of server to which rmilter should send all messages copies
        #copy_server = somehost:13333;

        # Address of server to which rmilter should send spam messages copies
        #spam_server = otherhost:13333;

        # Beanstalk protocol
        protocol = tcp;
        # Time to live for task in seconds
        lifetime = 172800;
        # Regexp that define for which messages we should put the whole message to beanstalk
        # now only In-Reply-To headers are checked
        id_regexp = "/^SomeID.*$/";
        # Flags for sending beanstalk copies
        send_beanstalk_headers = yes;
        send_beanstalk_copy = yes;
        send_beanstalk_spam = yes;
};

greylisting {
        timeout = 300s;
        expire = 3d;
        whitelist = 127.0.0.1;
        awl_enable = yes;
        awl_pool = 10M;
        awl_hits = 10;
        awl_ttl = 3600s;
};

dkim {
        # Sample for dkim specific keys
        # domain {
        #   key = /etc/dkim/dkim_example.key;
        #   domain = "example.com";
        #       selector = "dkim";
        # };
        # domain {
        #   key = /etc/dkim/dkim_test.key;
        #   domain = "test.com";
        #       selector = "dkim";
        # };
        # Universal selector, keys will be checked for pattern /etc/dkim/<domain>.<selector>.key
    domain {
                key = /etc/dkim;
                domain = "*";
                selector = "dkim";
        };
    header_canon = relaxed;
    body_canon = relaxed;
    sign_alg = sha256;
};

# Order of checks at EOM:
# 
# SPF -> DCC -> CLAMAV

**Comment by chromerobv** [comment]
ok. the config formatting got all screwed up sorry abut that. it wouldnt let me attach it and im not sure how to fix it.

**Comment by vstakhov** [comment]
What are the MTA source IP addresses for the first and subsequent attempts of sending.

**Comment by Safari77** [comment]
with 1.7.2, greylisting does not work.  
milter-reject: END-OF-MESSAGE from f5nat-luu.hard.ware.fi[178.217.130.7]: 4.7.1 Try again later; from=<x@luukku.com> to:<x@y> proto=ESMTP helo=<mta-out-12.luukku.com>
attempts were made Jan 24 11:10:39, Jan 24 11:30:51, Jan 24 11:51:50, Jan 24 12:33:50, Jan 24 13:57:51, Jan 24 16:45:51, Jan 24 22:21:54, Jan 25 09:34:01.  memcached has been running since 20 Jan.

**Comment by vixns** [comment]
I also have greylisting trouble with google. As explained in https://support.google.com/mail/answer/180063?hl=en, google may never use the initial IP in subsequent retries.

What about using a fingerprint ( e.g md5 of `subject + return-path + to + date` headers ) instead of IP address  as greylist key ? 

Or, as suggested by google, be able to add whole domains to greylisting's whitelist  ?

**Comment by vstakhov** [comment]
Rmilter already stores data hash for that purposes.

**Comment by vstakhov** [comment]
It seems that I've found an issue with data hash greylisting. It should be fixed by now.

**Comment by falstaff84** [comment]
Something is still not right with greylisting. I (still) use memcached, and messages get greylisted over and over again. Source IP, message ID and spamd scan result are identical, but greylisting_check_hash reports different hashes (and hence adds a new record).

**Comment by vstakhov** [comment]
I've investigated this issue and it turns out that it is related to memcached. Switching to redis should help.
